# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Users/yaozy/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/211.6693.114/CLion.app/Contents/bin/cmake/mac/bin/cmake"

# The command to remove a file.
RM = "/Users/yaozy/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/211.6693.114/CLion.app/Contents/bin/cmake/mac/bin/cmake" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/yaozy/Documents/code/Cpp/Base

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/yaozy/Documents/code/Cpp/Base

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Users/yaozy/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/211.6693.114/CLion.app/Contents/bin/cmake/mac/bin/cmake" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	"/Users/yaozy/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/211.6693.114/CLion.app/Contents/bin/cmake/mac/bin/cmake" -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yaozy/Documents/code/Cpp/Base/CMakeFiles /Users/yaozy/Documents/code/Cpp/Base//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yaozy/Documents/code/Cpp/Base/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Base

# Build rule for target.
Base: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Base
.PHONY : Base

# fast build rule for target.
Base/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/build
.PHONY : Base/fast

Buffer.o: Buffer.cpp.o

.PHONY : Buffer.o

# target to build an object file
Buffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/Buffer.cpp.o
.PHONY : Buffer.cpp.o

Buffer.i: Buffer.cpp.i

.PHONY : Buffer.i

# target to preprocess a source file
Buffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/Buffer.cpp.i
.PHONY : Buffer.cpp.i

Buffer.s: Buffer.cpp.s

.PHONY : Buffer.s

# target to generate assembly for a file
Buffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/Buffer.cpp.s
.PHONY : Buffer.cpp.s

Curl.o: Curl.cpp.o

.PHONY : Curl.o

# target to build an object file
Curl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/Curl.cpp.o
.PHONY : Curl.cpp.o

Curl.i: Curl.cpp.i

.PHONY : Curl.i

# target to preprocess a source file
Curl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/Curl.cpp.i
.PHONY : Curl.cpp.i

Curl.s: Curl.cpp.s

.PHONY : Curl.s

# target to generate assembly for a file
Curl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/Curl.cpp.s
.PHONY : Curl.cpp.s

DataPacket.o: DataPacket.cpp.o

.PHONY : DataPacket.o

# target to build an object file
DataPacket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/DataPacket.cpp.o
.PHONY : DataPacket.cpp.o

DataPacket.i: DataPacket.cpp.i

.PHONY : DataPacket.i

# target to preprocess a source file
DataPacket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/DataPacket.cpp.i
.PHONY : DataPacket.cpp.i

DataPacket.s: DataPacket.cpp.s

.PHONY : DataPacket.s

# target to generate assembly for a file
DataPacket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/DataPacket.cpp.s
.PHONY : DataPacket.cpp.s

JsonCodeCreator.o: JsonCodeCreator.cpp.o

.PHONY : JsonCodeCreator.o

# target to build an object file
JsonCodeCreator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/JsonCodeCreator.cpp.o
.PHONY : JsonCodeCreator.cpp.o

JsonCodeCreator.i: JsonCodeCreator.cpp.i

.PHONY : JsonCodeCreator.i

# target to preprocess a source file
JsonCodeCreator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/JsonCodeCreator.cpp.i
.PHONY : JsonCodeCreator.cpp.i

JsonCodeCreator.s: JsonCodeCreator.cpp.s

.PHONY : JsonCodeCreator.s

# target to generate assembly for a file
JsonCodeCreator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/JsonCodeCreator.cpp.s
.PHONY : JsonCodeCreator.cpp.s

Log.o: Log.cpp.o

.PHONY : Log.o

# target to build an object file
Log.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/Log.cpp.o
.PHONY : Log.cpp.o

Log.i: Log.cpp.i

.PHONY : Log.i

# target to preprocess a source file
Log.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/Log.cpp.i
.PHONY : Log.cpp.i

Log.s: Log.cpp.s

.PHONY : Log.s

# target to generate assembly for a file
Log.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/Log.cpp.s
.PHONY : Log.cpp.s

Pool.o: Pool.cpp.o

.PHONY : Pool.o

# target to build an object file
Pool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/Pool.cpp.o
.PHONY : Pool.cpp.o

Pool.i: Pool.cpp.i

.PHONY : Pool.i

# target to preprocess a source file
Pool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/Pool.cpp.i
.PHONY : Pool.cpp.i

Pool.s: Pool.cpp.s

.PHONY : Pool.s

# target to generate assembly for a file
Pool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/Pool.cpp.s
.PHONY : Pool.cpp.s

Tools.o: Tools.cpp.o

.PHONY : Tools.o

# target to build an object file
Tools.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/Tools.cpp.o
.PHONY : Tools.cpp.o

Tools.i: Tools.cpp.i

.PHONY : Tools.i

# target to preprocess a source file
Tools.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/Tools.cpp.i
.PHONY : Tools.cpp.i

Tools.s: Tools.cpp.s

.PHONY : Tools.s

# target to generate assembly for a file
Tools.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/Tools.cpp.s
.PHONY : Tools.cpp.s

cJSON.o: cJSON.c.o

.PHONY : cJSON.o

# target to build an object file
cJSON.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/cJSON.c.o
.PHONY : cJSON.c.o

cJSON.i: cJSON.c.i

.PHONY : cJSON.i

# target to preprocess a source file
cJSON.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/cJSON.c.i
.PHONY : cJSON.c.i

cJSON.s: cJSON.c.s

.PHONY : cJSON.s

# target to generate assembly for a file
cJSON.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/cJSON.c.s
.PHONY : cJSON.c.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Base"
	@echo "... Buffer.o"
	@echo "... Buffer.i"
	@echo "... Buffer.s"
	@echo "... Curl.o"
	@echo "... Curl.i"
	@echo "... Curl.s"
	@echo "... DataPacket.o"
	@echo "... DataPacket.i"
	@echo "... DataPacket.s"
	@echo "... JsonCodeCreator.o"
	@echo "... JsonCodeCreator.i"
	@echo "... JsonCodeCreator.s"
	@echo "... Log.o"
	@echo "... Log.i"
	@echo "... Log.s"
	@echo "... Pool.o"
	@echo "... Pool.i"
	@echo "... Pool.s"
	@echo "... Tools.o"
	@echo "... Tools.i"
	@echo "... Tools.s"
	@echo "... cJSON.o"
	@echo "... cJSON.i"
	@echo "... cJSON.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

