# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.20.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.20.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/yaozy/Documents/code/Cpp/Base

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/yaozy/Documents/code/Cpp/Base

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.20.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.20.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yaozy/Documents/code/Cpp/Base/CMakeFiles /Users/yaozy/Documents/code/Cpp/Base//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yaozy/Documents/code/Cpp/Base/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Base

# Build rule for target.
Base: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Base
.PHONY : Base

# fast build rule for target.
Base/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/build
.PHONY : Base/fast

Net/SocketOpt.o: Net/SocketOpt.cpp.o
.PHONY : Net/SocketOpt.o

# target to build an object file
Net/SocketOpt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/Net/SocketOpt.cpp.o
.PHONY : Net/SocketOpt.cpp.o

Net/SocketOpt.i: Net/SocketOpt.cpp.i
.PHONY : Net/SocketOpt.i

# target to preprocess a source file
Net/SocketOpt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/Net/SocketOpt.cpp.i
.PHONY : Net/SocketOpt.cpp.i

Net/SocketOpt.s: Net/SocketOpt.cpp.s
.PHONY : Net/SocketOpt.s

# target to generate assembly for a file
Net/SocketOpt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/Net/SocketOpt.cpp.s
.PHONY : Net/SocketOpt.cpp.s

Public/Buffer.o: Public/Buffer.cpp.o
.PHONY : Public/Buffer.o

# target to build an object file
Public/Buffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/Public/Buffer.cpp.o
.PHONY : Public/Buffer.cpp.o

Public/Buffer.i: Public/Buffer.cpp.i
.PHONY : Public/Buffer.i

# target to preprocess a source file
Public/Buffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/Public/Buffer.cpp.i
.PHONY : Public/Buffer.cpp.i

Public/Buffer.s: Public/Buffer.cpp.s
.PHONY : Public/Buffer.s

# target to generate assembly for a file
Public/Buffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/Public/Buffer.cpp.s
.PHONY : Public/Buffer.cpp.s

Public/Curl.o: Public/Curl.cpp.o
.PHONY : Public/Curl.o

# target to build an object file
Public/Curl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/Public/Curl.cpp.o
.PHONY : Public/Curl.cpp.o

Public/Curl.i: Public/Curl.cpp.i
.PHONY : Public/Curl.i

# target to preprocess a source file
Public/Curl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/Public/Curl.cpp.i
.PHONY : Public/Curl.cpp.i

Public/Curl.s: Public/Curl.cpp.s
.PHONY : Public/Curl.s

# target to generate assembly for a file
Public/Curl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/Public/Curl.cpp.s
.PHONY : Public/Curl.cpp.s

Public/DataPacket.o: Public/DataPacket.cpp.o
.PHONY : Public/DataPacket.o

# target to build an object file
Public/DataPacket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/Public/DataPacket.cpp.o
.PHONY : Public/DataPacket.cpp.o

Public/DataPacket.i: Public/DataPacket.cpp.i
.PHONY : Public/DataPacket.i

# target to preprocess a source file
Public/DataPacket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/Public/DataPacket.cpp.i
.PHONY : Public/DataPacket.cpp.i

Public/DataPacket.s: Public/DataPacket.cpp.s
.PHONY : Public/DataPacket.s

# target to generate assembly for a file
Public/DataPacket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/Public/DataPacket.cpp.s
.PHONY : Public/DataPacket.cpp.s

Public/Log.o: Public/Log.cpp.o
.PHONY : Public/Log.o

# target to build an object file
Public/Log.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/Public/Log.cpp.o
.PHONY : Public/Log.cpp.o

Public/Log.i: Public/Log.cpp.i
.PHONY : Public/Log.i

# target to preprocess a source file
Public/Log.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/Public/Log.cpp.i
.PHONY : Public/Log.cpp.i

Public/Log.s: Public/Log.cpp.s
.PHONY : Public/Log.s

# target to generate assembly for a file
Public/Log.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/Public/Log.cpp.s
.PHONY : Public/Log.cpp.s

Public/Tools.o: Public/Tools.cpp.o
.PHONY : Public/Tools.o

# target to build an object file
Public/Tools.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/Public/Tools.cpp.o
.PHONY : Public/Tools.cpp.o

Public/Tools.i: Public/Tools.cpp.i
.PHONY : Public/Tools.i

# target to preprocess a source file
Public/Tools.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/Public/Tools.cpp.i
.PHONY : Public/Tools.cpp.i

Public/Tools.s: Public/Tools.cpp.s
.PHONY : Public/Tools.s

# target to generate assembly for a file
Public/Tools.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/Public/Tools.cpp.s
.PHONY : Public/Tools.cpp.s

Public/cJSON.o: Public/cJSON.c.o
.PHONY : Public/cJSON.o

# target to build an object file
Public/cJSON.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/Public/cJSON.c.o
.PHONY : Public/cJSON.c.o

Public/cJSON.i: Public/cJSON.c.i
.PHONY : Public/cJSON.i

# target to preprocess a source file
Public/cJSON.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/Public/cJSON.c.i
.PHONY : Public/cJSON.c.i

Public/cJSON.s: Public/cJSON.c.s
.PHONY : Public/cJSON.s

# target to generate assembly for a file
Public/cJSON.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/Public/cJSON.c.s
.PHONY : Public/cJSON.c.s

Thread/Pool.o: Thread/Pool.cpp.o
.PHONY : Thread/Pool.o

# target to build an object file
Thread/Pool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/Thread/Pool.cpp.o
.PHONY : Thread/Pool.cpp.o

Thread/Pool.i: Thread/Pool.cpp.i
.PHONY : Thread/Pool.i

# target to preprocess a source file
Thread/Pool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/Thread/Pool.cpp.i
.PHONY : Thread/Pool.cpp.i

Thread/Pool.s: Thread/Pool.cpp.s
.PHONY : Thread/Pool.s

# target to generate assembly for a file
Thread/Pool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/Thread/Pool.cpp.s
.PHONY : Thread/Pool.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Base.dir/build.make CMakeFiles/Base.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Base"
	@echo "... Net/SocketOpt.o"
	@echo "... Net/SocketOpt.i"
	@echo "... Net/SocketOpt.s"
	@echo "... Public/Buffer.o"
	@echo "... Public/Buffer.i"
	@echo "... Public/Buffer.s"
	@echo "... Public/Curl.o"
	@echo "... Public/Curl.i"
	@echo "... Public/Curl.s"
	@echo "... Public/DataPacket.o"
	@echo "... Public/DataPacket.i"
	@echo "... Public/DataPacket.s"
	@echo "... Public/Log.o"
	@echo "... Public/Log.i"
	@echo "... Public/Log.s"
	@echo "... Public/Tools.o"
	@echo "... Public/Tools.i"
	@echo "... Public/Tools.s"
	@echo "... Public/cJSON.o"
	@echo "... Public/cJSON.i"
	@echo "... Public/cJSON.s"
	@echo "... Thread/Pool.o"
	@echo "... Thread/Pool.i"
	@echo "... Thread/Pool.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

